<div class="container-fluid footercpt">
<div class="container">
<div class="row">
<div class="col-lg-12"><img id="logoBlanco" src="https://imagineercx.net/cuero/pub/media/cuero-papel-tijera-logo-blanco.png" alt="Logo Cuero, Papel y Tijera"></div>
<div class="col-lg-4 listaFooter">
<ul>
<li><a href="/sofia-protti?___store=us" alt="Sofia Protti">Sofía Protti</a></li>

<li><a href="/get-to-know-us?___store=us" alt="Get to know us">Get to know us</a></li>

<li><a href="/blog?___store=us" alt="Blog">Blog</a></li>

<li><a href="/stores?___store=us" alt="Stores">Stores</a></li>

</ul>

</div>

<div class="col-lg-4">
<div class="redesSociales">
<a href="https://www.facebook.com/cueropapeltijera/"><img class="redesSocialesAll" src="https://imagineercx.net/cuero/pub/media/logo-facebook.png" alt=""> </a>
<a href="https://instagram.com/cueropapelytijera?igshid=1e6i92q3vf43k"><img class="redesSocialesAll" src="https://imagineercx.net/cuero/pub/media/logo-instagram.png" alt=""></a> 
<a href="https://www.waze.com/ul?ll=9.93958200%2C-84.10612600&navigate=yes"><img class="redesSocialesAll" src="https://imagineercx.net/cuero/pub/media/waze.png" alt=""></a>
</div> 
<img class="separadorFooter" src="https://imagineercx.net/cuero/pub/media/separador-footer.png" alt=""></div>

<div class="col-lg-4 listaFooter">

<ul>
<li><a href="/contact-us?___store=us" alt="Contact us">Contact us</a></li>
<li><a href="/changes?___store=us" alt="Changes policy">Changes policy</a></li>
<li><a href="/service?___store=us" alt="Terms and Conditions">Terms and conditions</a></li>
<li><a href="/privacy?___store=us" alt="Privacy policy">Privacy policy</a></li>

</ul>

</div>

</div>

<div class="row">

<div class="col-lg-4">&nbsp;</div>

<div class="col-lg-4">

<h4 id="suscribirseFooter">Subscribe to our newsletter</h4>

<form><input id="correoFooter" name="email" type="text" placeholder="Email"> <input id="suscribirme" type="submit" value="Subscribe"></form></div>

<div class="col-lg-4">&nbsp;</div>

</div>

</div>

</div>


